server:
  port: 80
  
## mysql
spring:
  datasource: ## jdbc:mysql://localhost:3306/jhta?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: ENC(YuaViDM4u41fFqm2LcHUyPWdKOKCWPMhsjoq2hJd5TYggEDNckqiJ/vuLviJCBOJmP8LBRcOc0VPFbXGS+AIbv8gRu9AHVHXQp/5Ts6C+UjeSqRvAoW/l0/0e7sP0SP7g12KbIBbYig=)
    username: ENC(9XDA7hCZmrSpgSMOeKNU1HcluBP0iYxE)
    password: ENC(LHl89g5NCgKgbPOU1S67Wbu5vFvDpZjC)
    driver-class-name: com.mysql.cj.jdbc.Driver

## email setting
  mail:
    host: smtp.gmail.com
    port: 587
    username: mgv0731@gmail.com
    password: imlfdeqsgtsgnkqb
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true

# mybatis
mybatis:
  mapper-locations:
    - mapper/*/*.xml
    - mapper/*.xml
  type-aliases-package: kr.co.mgv
  configuration:
    jdbc-type-for-null: 'NULL'
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    '[org.springframework-security]': trace
    '[kr.co.mgv.dao]': trace
    '[kr.co.mgv.board.mapper]': trace
    '[kr.co.mgv.movie.dao]': trace
    '[kr.co.mgv.store.mapper]': trace
    '[kr.co.mgv.support.dao]': trace
    '[kr.co.mgv.theater.dao]': trace
    '[kr.co.mgv.user.mapper]': trace
    '[kr.co.mgv.schedule.dao]': trace
---
## thymeleaf
spring:
  thymeleaf:
    cache: false

    
    
